//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelP.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About us.
        /// </summary>
        public static string ButtonAboutUs {
            get {
                return ResourceManager.GetString("ButtonAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AdminMenu.
        /// </summary>
        public static string ButtonAdminMenu {
            get {
                return ResourceManager.GetString("ButtonAdminMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buy.
        /// </summary>
        public static string ButtonBuy {
            get {
                return ResourceManager.GetString("ButtonBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find.
        /// </summary>
        public static string ButtonFind {
            get {
                return ResourceManager.GetString("ButtonFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find an order.
        /// </summary>
        public static string ButtonFinder {
            get {
                return ResourceManager.GetString("ButtonFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shop.
        /// </summary>
        public static string ButtonShop {
            get {
                return ResourceManager.GetString("ButtonShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your contact details.
        /// </summary>
        public static string HeaderContact {
            get {
                return ResourceManager.GetString("HeaderContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the start and end date of the booking.
        /// </summary>
        public static string HeaderSE {
            get {
                return ResourceManager.GetString("HeaderSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order access key:.
        /// </summary>
        public static string LabelAcessKey {
            get {
                return ResourceManager.GetString("LabelAcessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Book before.
        /// </summary>
        public static string LabelBookBefore {
            get {
                return ResourceManager.GetString("LabelBookBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Booked before.
        /// </summary>
        public static string LabelBookedBefore {
            get {
                return ResourceManager.GetString("LabelBookedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Booked from.
        /// </summary>
        public static string LabelBookedFrom {
            get {
                return ResourceManager.GetString("LabelBookedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Book from.
        /// </summary>
        public static string LabelBookFrom {
            get {
                return ResourceManager.GetString("LabelBookFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Characteristic.
        /// </summary>
        public static string LabelCharacteristic {
            get {
                return ResourceManager.GetString("LabelCharacteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на City:.
        /// </summary>
        public static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clarification of the order.
        /// </summary>
        public static string LabelClarification {
            get {
                return ResourceManager.GetString("LabelClarification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the order code.
        /// </summary>
        public static string LabelCodeOrder {
            get {
                return ResourceManager.GetString("LabelCodeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cost:.
        /// </summary>
        public static string LabelCost {
            get {
                return ResourceManager.GetString("LabelCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count of rooms:.
        /// </summary>
        public static string LabelCount {
            get {
                return ResourceManager.GetString("LabelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer&apos;s email:.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location:.
        /// </summary>
        public static string LabelLocation {
            get {
                return ResourceManager.GetString("LabelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order number:.
        /// </summary>
        public static string LabelNomber {
            get {
                return ResourceManager.GetString("LabelNomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the order number:.
        /// </summary>
        public static string LabelNomOrder {
            get {
                return ResourceManager.GetString("LabelNomOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The order was not found.
        /// </summary>
        public static string LabelNotFound {
            get {
                return ResourceManager.GetString("LabelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not found.
        /// </summary>
        public static string LabelNotFoundNoOrder {
            get {
                return ResourceManager.GetString("LabelNotFoundNoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer&apos;s number:.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prices before.
        /// </summary>
        public static string LabelPricesB {
            get {
                return ResourceManager.GetString("LabelPricesB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prices from.
        /// </summary>
        public static string LabelPricesF {
            get {
                return ResourceManager.GetString("LabelPricesF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на . Remeber him!.
        /// </summary>
        public static string LabelRemeber {
            get {
                return ResourceManager.GetString("LabelRemeber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Room&apos;s nomber:.
        /// </summary>
        public static string LabelRoomNumber {
            get {
                return ResourceManager.GetString("LabelRoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After clicking on the buy button and confirming the payment, a code will appear for your number. Remember him!!!.
        /// </summary>
        public static string LabelWarning {
            get {
                return ResourceManager.GetString("LabelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome!!!.
        /// </summary>
        public static string LabelWelcome {
            get {
                return ResourceManager.GetString("LabelWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can&apos;t go back!.
        /// </summary>
        public static string MessageCB {
            get {
                return ResourceManager.GetString("MessageCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a date!.
        /// </summary>
        public static string MessBChooseDate {
            get {
                return ResourceManager.GetString("MessBChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning!.
        /// </summary>
        public static string MessBWarning {
            get {
                return ResourceManager.GetString("MessBWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotel.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This program is designed to develop programming skills and show the possibilities of these skills. The program is not designed to offend anyone or steal anyone&apos;s ideas..
        /// </summary>
        public static string TextAboutUs {
            get {
                return ResourceManager.GetString("TextAboutUs", resourceCulture);
            }
        }
    }
}
