//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int IDBooking { get; set; }
        public int IDRoom { get; set; }
        public string KeyRoom { get; set; }
        public System.DateTime BookingWhen { get; set; }
        public System.DateTime BookingIn { get; set; }
        public System.DateTime BookingOut { get; set; }
        public string EmailOrPhone { get; set; }
    
        public virtual HotelRooms HotelRooms { get; set; }
    }
}
