//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelP
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelRooms()
        {
            this.Bookings = new HashSet<Bookings>();
        }
    
        public int IDRoom { get; set; }
        public int IDHotel { get; set; }
        public int Cost { get; set; }
        public string Coments { get; set; }
        public int RoomsCount { get; set; }
        public string TakedTimes { get; set; }
        public byte[] ImageRoom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual Hotels Hotels { get; set; }
    }
}
